userpassDict = {
'pcp_port': 9898,
'pcp_user': 'pcpuser',
'pcp_password': 'mypass',
'pool_port': 5432,
'pool_user': 'admin',
'pool_password': 'dbod-postgres-test',
'recovery_user': 'duper',
'recovery_password': 'superduper',
'sr_check_user': 'checker',
'sr_check_password': 'test',
'sr_check_database': 'checker',
'health_check_user': 'checker',
'health_check_password': 'test',
'health_check_database': 'checker',
}
